In [1]:
!git clone https://github.com/niazwazir/TESTING_IMAGES.git

Cloning into 'TESTING_IMAGES'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 60 (delta 11), reused 8 (delta 8), pack-reused 48
Receiving objects: 100% (60/60), 27.65 MiB | 30.38 MiB/s, done.
Resolving deltas: 100% (13/13), done.


In [2]:
!ls

sample_data  TESTING_IMAGES


In [3]:
cd TESTING_IMAGES/

/content/TESTING_IMAGES


In [4]:
!ls

baby_x2_bicubic.png  baby_x2_SRCNN.png	HR	       Supavadee.png
baby_x2_GT.png	     BUTTERFLY.png	SPLITTING.png  WAZIR_MODEL_IMAGES


In [5]:
cd HR

/content/TESTING_IMAGES/HR


In [6]:
!ls

01.png	02.png	03.png	04.png	05.png	49.png	51.png	56.png	58.png	60.png


In [7]:
cd ..

/content/TESTING_IMAGES


In [8]:
!ls

baby_x2_bicubic.png  baby_x2_SRCNN.png	HR	       Supavadee.png
baby_x2_GT.png	     BUTTERFLY.png	SPLITTING.png  WAZIR_MODEL_IMAGES


In [9]:
import numpy as np
import cv2
import os

IMG_DIR = 'HR'

for img in os.listdir(IMG_DIR):
        img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)

        img_array = (img_array.flatten())

        img_array  = img_array.reshape(-1, 1).T

        print(img_array)

        with open('output.csv', 'ab') as f:

            np.savetxt(f, img_array, delimiter=",")

[[104 101 103 ... 134  77  50]]
[[154 129 106 ... 130 132 137]]
[[213 213 213 ...  88  86  83]]
[[171 171 170 ... 199 194 190]]
[[192 192 191 ... 118 119 118]]
[[107 108 106 ... 116 112 118]]
[[103  92 111 ... 111 116 117]]
[[207 207 206 ... 134 133 140]]
[[184 183 183 ... 104 121 131]]
[[121 121 112 ... 137 138 141]]


In [10]:
!ls

baby_x2_bicubic.png  baby_x2_SRCNN.png	HR	    SPLITTING.png  WAZIR_MODEL_IMAGES
baby_x2_GT.png	     BUTTERFLY.png	output.csv  Supavadee.png
